#+SETUPFILE: ./Setup/setupFile.org
#+TITLE: Direct Convolution Package
#+PROPERTY: header-args:julia :session *directConvolution_session*  :exports code :eval no-export


#+BEGIN_EXPORT latex
\definecolor{bg}{rgb}{0.95,0.95,0.95}
\setminted[]{
  bgcolor=bg,
  breaklines=true,
  breakanywhere=true,
  mathescape,
  fontsize=\footnotesize}
#+END_EXPORT

#+BEGIN_SRC julia :exports none
using Plots
using Revise
using DirectConvolution
using J4Org

documented_items=create_documented_item_array_dir("~/GitHub/DirectConvolution.jl/src/");
#+END_SRC

#+RESULTS:

* Introduction

This package goal is to compute convolution products 

\begin{equation}
\label{eq:main}
\gamma[k]=\sum\limits_{i\in\Omega^\alpha}\alpha[i]\beta[k+\lambda i],\text{ with }\lambda\in\mathbb{Z}^*
\end{equation}

using direct (no FFT) methods. 

* API documentation
** Linear Filter

#+BEGIN_SRC julia :results output drawer :eval no-export :exports results
documented_items=create_documented_item_array_dir("~/GitHub/DirectConvolution.jl/src/");
print_org_doc(documented_items,tag="LinearFilter",header_level=0)
#+END_SRC

#+RESULTS:
:RESULTS:

<<T1DnLSIE>> *Index:* *[E]* [[1qhtfrBA][export]] *[F]* [[J0MDu9EM][fcoef]] *[L]* [[OTixcqQr][length]], [[mu1LQ7xX][LinearFilter]], [[40yTpDAq][LinearFilter_Default]], [[IX8gnh1U][LinearFilter_DefaultCentered]] *[O]* [[fsShwstR][offset]] *[R]* [[QAwhsMWR][range]] 
- @@latex:\phantomsection@@ *=export=*  <<1qhtfrBA>>
#+BEGIN_SRC julia :eval never :exports code
export LinearFilter,LinearFilter_Default, LinearFilter_CenteredDefault,
    fcoef, length, offset, range
#+END_SRC
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::1][linearFilter.jl]], [[T1DnLSIE][back to index]]
- @@latex:\phantomsection@@ *=fcoef=*  <<J0MDu9EM>>
#+BEGIN_SRC julia :eval never :exports code
fcoef(c::LinearFilter)
#+END_SRC
#+BEGIN_QUOTE
Returns filter coefficients as a Vector type 
#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::13][linearFilter.jl]], [[T1DnLSIE][back to index]]
- @@latex:\phantomsection@@ *=length=*  <<OTixcqQr>>
#+BEGIN_SRC julia :eval never :exports code
length(c::LinearFilter)
#+END_SRC
#+BEGIN_QUOTE
Returns filter length
#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::16][linearFilter.jl]], [[T1DnLSIE][back to index]]
- @@latex:\phantomsection@@ *=LinearFilter=*  <<mu1LQ7xX>>
#+BEGIN_SRC julia :eval never :exports code
abstract type LinearFilter{T<:Number} 
#+END_SRC
#+BEGIN_QUOTE
Abstract type defining a linear filter
#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::8][linearFilter.jl]], [[T1DnLSIE][back to index]]
- @@latex:\phantomsection@@ *=LinearFilter_Default=*  <<40yTpDAq>>
#+BEGIN_SRC julia :eval never :exports code
struct LinearFilter_Default{T<:AbstractFloat,N} <: LinearFilter{T}
#+END_SRC
#+BEGIN_QUOTE
Default linear filter
#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::36][linearFilter.jl]], [[T1DnLSIE][back to index]]
#+BEGIN_SRC julia :eval never :exports code
function LinearFilter_Default(c::AbstractArray{T,1},offset::Int)  where {T<:AbstractFloat}
#+END_SRC
#+BEGIN_QUOTE
Creates a linear filter from a coefficient vector and its associated offset
#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::43][linearFilter.jl]], [[T1DnLSIE][back to index]]
- @@latex:\phantomsection@@ *=LinearFilter_DefaultCentered=*  <<IX8gnh1U>>
#+BEGIN_SRC julia :eval never :exports code
struct LinearFilter_DefaultCentered{T<:AbstractFloat,N} <: LinearFilter{T}
#+END_SRC
#+BEGIN_QUOTE
Provides a default implementation of size 2n+1, with offset = n

#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::52][linearFilter.jl]], [[T1DnLSIE][back to index]]
#+BEGIN_SRC julia :eval never :exports code
function LinearFilter_DefaultCentered(c::Array{T}) where {T<:AbstractFloat}
#+END_SRC
#+BEGIN_QUOTE
Creates a centered linear filter from an array of size = 2n+1

#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::59][linearFilter.jl]], [[T1DnLSIE][back to index]]
- @@latex:\phantomsection@@ *=offset=*  <<fsShwstR>>
#+BEGIN_SRC julia :eval never :exports code
offset(c::LinearFilter)
#+END_SRC
#+BEGIN_QUOTE
Returns filter offset
#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::19][linearFilter.jl]], [[T1DnLSIE][back to index]]
#+BEGIN_SRC julia :eval never :exports code
offset(f::LinearFilter_DefaultCentered{T,N}) where {T<:AbstractFloat,N}
#+END_SRC
#+BEGIN_QUOTE
Returns offset, if size = 2n+1 then offset = n

#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::68][linearFilter.jl]], [[T1DnLSIE][back to index]]
- @@latex:\phantomsection@@ *=range=*  <<QAwhsMWR>>
#+BEGIN_SRC julia :eval never :exports code
range(c::LinearFilter)
#+END_SRC
#+BEGIN_QUOTE
Returns filter range
#+END_QUOTE
[[file:/home/picaud/GitHub/DirectConvolution.jl/src/linearFilter.jl::22][linearFilter.jl]], [[T1DnLSIE][back to index]]
:END:

** Undecimated Wavelet Transform
*** UDWT Filters
 #+BEGIN_SRC julia :results output drawer :eval no-export :exports results
documented_items=create_documented_item_array_dir("~/GitHub/DirectConvolution.jl/src/");
print_org_doc(documented_items,tag="UDWT_Filter",header_level=0)
 #+END_SRC

 #+RESULTS:
 :RESULTS:

 <<F8rkxPv9>> *Index:* *[E]* [[CYPZs1Em][export]] *[T]* [[oV0K7HkG][tildeϕ_filter]], [[VmbUuKj4][tildeϕ_offset]], [[pnI1DN0h][tildeψ_filter]], [[W6LdbdKs][tildeψ_offset]] *[U]* [[hQPAhgUR][UDWT_Filter]], [[P1fxe5k8][UDWT_Filter_Biorthogonal]], [[sNylSAR2][UDWT_Filter_Haar]], [[XdMujVCT][UDWT_Filter_Starck2]] *[Φ]* [[koL31hLU][ϕ_filter]], [[VXCyWqhc][ϕ_offset]] *[Ψ]* [[gY4b6cQ0][ψ_filter]], [[aEo2ISoX][ψ_offset]] 
 - @@latex:\phantomsection@@ *=export=*  <<CYPZs1Em>>
 #+BEGIN_SRC julia :eval never :exports code
 export UDWT_Filter_Haar, UDWT_Filter_Starck2
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::1][udwt.jl]], [[F8rkxPv9][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 export ϕ_filter,ψ_filter,tildeϕ_filter,tildeψ_filter,ϕ_offset,ψ_offset,tildeϕ_offset,tildeψ_offset
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::3][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=tildeϕ_filter=*  <<oV0K7HkG>>
 #+BEGIN_SRC julia :eval never :exports code
 tildeϕ_filter(c::UDWT_Filter_Biorthogonal)::LinearFilter
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::25][udwt.jl]], [[F8rkxPv9][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 tildeϕ_filter(c::UDWT_Filter)::LinearFilter
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::50][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=tildeϕ_offset=*  <<VmbUuKj4>>
 #+BEGIN_SRC julia :eval never :exports code
 tildeϕ_offset(c::UDWT_Filter_Biorthogonal)::Int
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::33][udwt.jl]], [[F8rkxPv9][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 tildeϕ_offset(c::UDWT_Filter)::Int
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::56][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=tildeψ_filter=*  <<pnI1DN0h>>
 #+BEGIN_SRC julia :eval never :exports code
 tildeψ_filter(c::UDWT_Filter_Biorthogonal)::LinearFilter
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::27][udwt.jl]], [[F8rkxPv9][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 tildeψ_filter(c::UDWT_Filter)::LinearFilter
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::53][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=tildeψ_offset=*  <<W6LdbdKs>>
 #+BEGIN_SRC julia :eval never :exports code
 tildeψ_offset(c::UDWT_Filter_Biorthogonal)::Int
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::35][udwt.jl]], [[F8rkxPv9][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 tildeψ_offset(c::UDWT_Filter)::Int
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::59][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=UDWT_Filter=*  <<hQPAhgUR>>
 #+BEGIN_SRC julia :eval never :exports code
 abstract type UDWT_Filter{T<:Number} <: UDWT_Filter_Biorthogonal{T}
 #+END_SRC
 #+BEGIN_QUOTE
 A specialization of UDWT_Filter_Biorthogonal for *orthogonal* filters.


 For orthogonal filters we have: $\phi=\tilde{\phi}$ and $\psi=\tilde{\psi}$

 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::40][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=UDWT_Filter_Biorthogonal=*  <<P1fxe5k8>>
 #+BEGIN_SRC julia :eval never :exports code
 abstract type UDWT_Filter_Biorthogonal{T<:Number} 
 #+END_SRC
 #+BEGIN_QUOTE
 Abstract type defining the $\phi$, $\psi$, $\tilde{\phi}$ and
 $\tilde{\psi}$ filters associated to an undecimated biorthogonal
 wavelet transform

 - [X] TODO must use LinearFilter struct 
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::12][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=UDWT_Filter_Haar=*  <<sNylSAR2>>
 #+BEGIN_SRC julia :eval never :exports code
 struct UDWT_Filter_Haar{T<:AbstractFloat} <: UDWT_Filter{T}
 #+END_SRC
 #+BEGIN_QUOTE
 Haar filter
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::66][udwt.jl]], [[F8rkxPv9][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 UDWT_Filter_Haar{T}() where {T<:Real}
 #+END_SRC
 #+BEGIN_QUOTE
 Creates an instance
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::72][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=UDWT_Filter_Starck2=*  <<XdMujVCT>>
 #+BEGIN_SRC julia :eval never :exports code
 struct UDWT_Filter_Starck2{T<:AbstractFloat} <: UDWT_Filter_Biorthogonal{T}
 #+END_SRC
 #+BEGIN_QUOTE
 Starck2 filter

 Defined by Eq. 6 from http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4060954
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::80][udwt.jl]], [[F8rkxPv9][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 UDWT_Filter_Starck2{T}() where {T<:Real}
 #+END_SRC
 #+BEGIN_QUOTE
 Creates an instance
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::90][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=ϕ_filter=*  <<koL31hLU>>
 #+BEGIN_SRC julia :eval never :exports code
 ϕ_filter(c::UDWT_Filter_Biorthogonal)::LinearFilter
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::21][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=ϕ_offset=*  <<VXCyWqhc>>
 #+BEGIN_SRC julia :eval never :exports code
 ϕ_offset(c::UDWT_Filter_Biorthogonal)::Int
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::29][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=ψ_filter=*  <<gY4b6cQ0>>
 #+BEGIN_SRC julia :eval never :exports code
 ψ_filter(c::UDWT_Filter_Biorthogonal)::LinearFilter
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::23][udwt.jl]], [[F8rkxPv9][back to index]]
 - @@latex:\phantomsection@@ *=ψ_offset=*  <<aEo2ISoX>>
 #+BEGIN_SRC julia :eval never :exports code
 ψ_offset(c::UDWT_Filter_Biorthogonal)::Int
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::31][udwt.jl]], [[F8rkxPv9][back to index]]
 :END:

*** UDWT Computational subroutines
 #+BEGIN_SRC julia :results output drawer :eval no-export :exports results
print_org_doc(documented_items,tag="UDWT",header_level=0)
 #+END_SRC

 #+RESULTS:
 :RESULTS:
 <<GXZw6TfF>> *Index:* *[E]* [[UazVD3px][export]] *[I]* [[LujkFwWG][inverse_udwt]], [[sRBhGdSp][inverse_udwt!]] *[L]* [[qMZ8YPPM][length]] *[S]* [[gWrysaiV][scale]] *[U]* [[c0MVINwl][UDWT]], [[2z3zaGRo][udwt]] 
 - @@latex:\phantomsection@@ *=export=*  <<UazVD3px>>
 #+BEGIN_SRC julia :eval never :exports code
 export udwt, scale, inverse_udwt!, inverse_udwt
 #+END_SRC
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::5][udwt.jl]], [[GXZw6TfF][back to index]]
 - @@latex:\phantomsection@@ *=inverse_udwt=*  <<LujkFwWG>>
 #+BEGIN_SRC julia :eval never :exports code
 function inverse_udwt(udwt_domain::UDWT{T})::Array{T,1} where {T<:Number}
 #+END_SRC
 #+BEGIN_QUOTE
 Performs an 1D *inverse* undecimated wavelet transform

 *Returns:* a vector containing the reconstructed signal.
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::250][udwt.jl]], [[GXZw6TfF][back to index]]
 - @@latex:\phantomsection@@ *=inverse_udwt!=*  <<sRBhGdSp>>
 #+BEGIN_SRC julia :eval never :exports code
 function inverse_udwt!(udwt_domain::UDWT{T},reconstructed_signal::AbstractArray{T,1}) where {T<:Number}
 #+END_SRC
 #+BEGIN_QUOTE
 Performs an 1D *inverse* undecimated wavelet transform

 *Caveat:* uses a pre-allocated vector =reconstructed_signal=
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::193][udwt.jl]], [[GXZw6TfF][back to index]]
 - @@latex:\phantomsection@@ *=length=*  <<qMZ8YPPM>>
 #+BEGIN_SRC julia :eval never :exports code
 length(udwt::UDWT)::Int
 #+END_SRC
 #+BEGIN_QUOTE
 Returns expected signal length
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::129][udwt.jl]], [[GXZw6TfF][back to index]]
 - @@latex:\phantomsection@@ *=scale=*  <<gWrysaiV>>
 #+BEGIN_SRC julia :eval never :exports code
 scale(udwt::UDWT)::Int
 #+END_SRC
 #+BEGIN_QUOTE
 Returns max scale
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::126][udwt.jl]], [[GXZw6TfF][back to index]]
 - @@latex:\phantomsection@@ *=UDWT=*  <<c0MVINwl>>
 #+BEGIN_SRC julia :eval never :exports code
 struct UDWT{T<:Number}
 #+END_SRC
 #+BEGIN_QUOTE
 A structure to store 1D UDWT
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::99][udwt.jl]], [[GXZw6TfF][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 UDWT{T}(filter::UDWT_Filter_Biorthogonal{T};
	     n::Int=0,
	     scale::Int=0) where {T<:Number}
 #+END_SRC
 #+BEGIN_QUOTE
 Creates an instance

 *Parameters:*
 - *filter*: used filter
 - *scale* : max scale
 - *n*: signal length
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::110][udwt.jl]], [[GXZw6TfF][back to index]]
 - @@latex:\phantomsection@@ *=udwt=*  <<2z3zaGRo>>
 #+BEGIN_SRC julia :eval never :exports code
 function udwt(signal::AbstractArray{T,1},filter::UDWT_Filter_Biorthogonal{T};scale::Int=3) where {T<:Number}
 #+END_SRC
 #+BEGIN_QUOTE
 Performs an 1D undecimated wavelet transform

 $$(\mathcal{W}_{j+1}f)[u]=(\bar{g}_j*\mathcal{V}_{j}f)[u]$$
 $$(\mathcal{V}_{j+1}f)[u]=(\bar{h}_j*\mathcal{V}_{j}f)[u]$$

 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/udwt.jl::133][udwt.jl]], [[GXZw6TfF][back to index]]
 :END:

** Convolution functions

These are the main functions of the package, allowing to compute Eq. \ref{eq:main}.

 #+BEGIN_SRC julia :results output drawer :eval no-export :exports results
documented_items=create_documented_item_array_dir("~/GitHub/DirectConvolution.jl/src/");
print_org_doc(documented_items,tag="Convolution",header_level=0)
 #+END_SRC

 #+RESULTS:
 :RESULTS:

 <<nJcbMYl5>> *Index:* *[D]* [[CTCC4Znj][directConv]], [[j95o90Tj][directConv!]] 
 - @@latex:\phantomsection@@ *=directConv=*  <<CTCC4Znj>>
 #+BEGIN_SRC julia :eval never :exports code
 function directConv(tilde_α::AbstractArray{T,1},
		     α_offset::Int64,
		     λ::Int64,

		     β::AbstractArray{T,1},

		     ::Type{LeftBE}=ZeroPaddingBE,
		     ::Type{RightBE}=ZeroPaddingBE) where {T <: Number,
							   LeftBE <: BoundaryExtension,
							   RightBE <: BoundaryExtension}
 #+END_SRC
 #+BEGIN_QUOTE
 Computes a convolution.

 Returns γ, a created vector of length identical to β one.
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/directConvolution.jl::242][directConvolution.jl]], [[nJcbMYl5][back to index]]
 - @@latex:\phantomsection@@ *=directConv!=*  <<j95o90Tj>>
 #+BEGIN_SRC julia :eval never :exports code
 function directConv!(tilde_α::AbstractArray{T,1},
		      α_offset::Int,
		      λ::Int,

		      β::AbstractArray{T,1},

		      γ::AbstractArray{T,1},
		      Ωγ::UnitRange{Int},

		      ::Type{LeftBE}=ZeroPaddingBE,
		      ::Type{RightBE}=ZeroPaddingBE;

		      accumulate::Bool=false) where {T <: Number,
						     LeftBE <: BoundaryExtension,
						     RightBE <: BoundaryExtension}
 #+END_SRC
 #+BEGIN_QUOTE
 Computes a convolution.

 Inplace modification of γ
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/directConvolution.jl::164][directConvolution.jl]], [[nJcbMYl5][back to index]]
 #+BEGIN_SRC julia :eval never :exports code
 function directConv!(α::LinearFilter{T},
		      λ::Int,

		      β::AbstractArray{T,1},

		      γ::AbstractArray{T,1},
		      Ωγ::UnitRange{Int},

		      ::Type{LeftBE}=ZeroPaddingBE,
		      ::Type{RightBE}=ZeroPaddingBE;

		      accumulate::Bool=false) where {T <: Number,
						     LeftBE <: BoundaryExtension,
						     RightBE <: BoundaryExtension}
 #+END_SRC
 #+BEGIN_QUOTE
 Computes a convolution.

 Takes a filter as input 

 Inplace modification of γ
 #+END_QUOTE
 [[file:/home/picaud/GitHub/DirectConvolution.jl/src/directConvolution.jl::202][directConvolution.jl]], [[nJcbMYl5][back to index]]
 :END:

* TODO [0/1]
- [ ] add example with derivative taking X into account

